### PR TITLE
Extended global flag bSizeOnly into status text generation

### PR DESCRIPTION
**Pull request by Bob837217**

### CODE REVIEW

**Comment by Bob837217** [comment]
The reason why I made the addition is that the status text generation performs a lot of md5 generation by default and these md5 results are discarded immediately after outputting to Status Text. On my GoG account + PC, this takes very close to 2 hours of grinding md5s to get the Status Text done.

After applying this change, the same command now only takes 1-2 minutes.

**Comment by fgaz** [comment]
Thanks for fixing this! I back up my games on a remote filesystem and was wondering why `lgogdownloader --status  --size-only` was transferring so much data. Now it's really fast!

Looks like `--download` is still affected though. It still reads through the whole file instead of checking only its size :-/

**Comment by Bob837217** [comment]
My pleasure mate. Nice to see some positive feedback.
I looked into --download and the issue present is that GoG reports both the MD5 hash and the file size for each file. And whilst the MD5 from GoG is correct, the size is wildly incorrect pretty much every time and it varies with a -ve and +ve delta at random for each file.  No idea what is up with that.

So you cannot rely upon GoG cloud file sizes thus the file size is saved into a .xml cache file by lgogdownloader (depending on your config flags).  If the cached xml value exists, that should be used.

For my usage to make the most efficient runs, I script --status into a file, then loop through all lines with anything besides the "OK" status indicator and thus only --download files that do not exist locally or have a different file size (compared with the xml cached size).

**Comment by fgaz** [comment]
> If the cached xml value exists, that should be used.

This does not happen in my experience, or there's something else in that still reads the file.

The full command I'm using is `lgogdownloader --download --game '^some_game_prefix' --save-changelogs --save-serials --xml-directory metadata --size-only --threads 1 --info-threads 1`. The file sizes appear to be correctly saved in the `metadata` directory, but on the second run lgogdownloader reads the downloaded files anyway.

**Comment by Bob837217** [comment]
Added my lgogdownloader "config.cfg" file with all settings present as "config.cfg.txt" (git only allows .txt amongst other select extensions as attachments here)

M cmdline is: `lgogdownloader --download --game ${gamename} --automatic-xml-creation`

[config.cfg.txt](https://github.com/Sude-/lgogdownloader/files/10561708/config.cfg.txt)

**Pull request merged**
